authors:
  stalecu:
    name: Ștefan-Iulian Alecu
  susan:
    name: Susan  
  stdasca:
    name: Ștefan-Cosmin Dăscălescu
  ioma:
    name: Matei Ionescu
  traian:
    name: Traian Danciu
  ivan:
    name: Andrei-Cristian Ivan   
  luca:
    name: Luca Mureșan
  anomori:
    name: Teodor Ștefan Manolea
  radu:
    name: Radu Mocănașu             